services:
  sqldata:
    image: mcr.microsoft.com/mssql/server
    # hostname: sqlserver
    container_name: sql-server
    ports:
      - 1433:1433
    command: bash -c "chmod -R 777 /usr/src/sql/ && /usr/src/sql/entrypoint.sh"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1234*
    volumes:
      - ./sql/:/usr/src/sql/

  customerapi:
    container_name: customers
    build:
      context: ./Customer
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - SERVERNAME=sqldata
      - DATABASE=OrderCustomer
      - PASSWORD=Password1234*
    volumes:
      - ./.aspnet/https:/https:ro
    depends_on:
      - sqldata

  orderapi:
    container_name: orders
    build:
      context: ./Order
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - SERVERNAME=sqldata
      - DATABASE=OrderCustomer
      - PASSWORD=Password1234*
    volumes:
      - ./.aspnet/https:/https:ro
    depends_on:
      - sqldata
